config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :orders
  resources :items
  devise_for :users
  root to: 'home#index'
end

app/models/item.rb
# An item is something that might be sold in the shop, such as an espresso
class Item < ActiveRecord::Base
  monetize :price_cents

  scope :all_except, ->(items) { where.not(id: items) }

  has_many :stock_effects, dependent: :delete_all
  accepts_nested_attributes_for :stock_effects

  validates :name, presence: true
  validates :price_cents, presence: true, numericality: { greater_than: 0 }

  before_validation :clear_zero_change_stock_effects

  def current_and_potential_stock_effects
    stock_effects + potential_stock_effects
  end

  private

  def potential_stock_effects
    accounted_for_stocks = stock_effects.map(&:stock)
    unaccounted_for_stocks = Stock.all_except(accounted_for_stocks)
    unaccounted_for_stocks.map { |stock| StockEffect.new(stock: stock) }
  end

  def clear_zero_change_stock_effects
    stock_effects.select(&:zero_change?).each(&:destroy)

    self.stock_effects = stock_effects.reject do |effect|
      (!effect.persisted?) && (effect.zero_change?)
    end
  end
end

app/models/line_item.rb
# A line item represents a part of an order that comprises several units of a given item,
# e.g. 2 espressos
class LineItem < ActiveRecord::Base
  monetize :price_at_purchase_cents

  belongs_to :order
  belongs_to :item

  validates :quantity, numericality: { greater_than: 0 }

  before_validation :set_price_at_purchase
  before_save :change_stock
  before_destroy :unchange_stock

  def total_price
    price_at_purchase * quantity
  end

  def zero_quantity?
    quantity.blank? || quantity.to_i == 0
  end

  private

  def change_stock
    item.stock_effects.each do |effect|
      delta = quantity - (quantity_was || 0)
      effect.stock.estimate = true
      effect.stock.decrement! :level, (effect.change * delta)
    end
  end

  def unchange_stock
    return unless item
    item.stock_effects.each do |effect|
      effect.stock.estimate = true
      effect.stock.increment! :level, (effect.change * quantity)
    end
  end

  def set_price_at_purchase
    self.price_at_purchase = item.price
  end
end

app/models/order.rb
# An order is what a customer asks for
class Order < ActiveRecord::Base
  paginates_per 30

  belongs_to :user
  has_many :line_items, dependent: :destroy
  accepts_nested_attributes_for :line_items

  validates :total_selected_items, numericality: { greater_than: 0 }

  before_validation :clear_zero_quantity_line_items

  def current_and_potential_line_items
    line_items + potential_line_items
  end

  def total
    @total ||= Money.new(total_cents)
  end

  private

  def potential_line_items
    accounted_for_items = line_items.map(&:item)
    unaccounted_for_items = Item.all_except(accounted_for_items)
    unaccounted_for_items.map { |item| LineItem.new(item: item) }
  end

  def clear_zero_quantity_line_items
    line_items.select(&:zero_quantity?).each(&:destroy)

    self.line_items = line_items.reject do |line_item|
      (!line_item.persisted?) && (line_item.zero_quantity?)
    end
  end

  def total_cents
    line_items.map(&:total_price).sum
  end

  def total_selected_items
    line_items.map(&:quantity).sum
  end
end

app/models/stock.rb
# A stock is a supply of materials used to prepare items. E.g. Coffee beans
class Stock < ActiveRecord::Base
  has_many :stock_effects

  scope :all_except, ->(stocks) { where.not(id: stocks) }

  validates :name,  presence: true
  validates :level, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :unit,  presence: true
end

app/models/stock_effect.rb
# A stock effect models how serving a given item reduces a
# given stock. E.g. an espresso might have a stock effect
# of reducing coffee beans by 25 grams.
class StockEffect < ActiveRecord::Base
  belongs_to :stock
  belongs_to :item

  validates :change, numericality: { greater_than: 0 }

  def zero_change?
    change.blank? || change.to_i == 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    load_items
  end

  def new
    build_item
  end

  def show
    load_item
  end

  def create
    build_item
    save_item || render(:new)
  end

  def edit
    load_item
    build_item
  end

  def update
    load_item
    build_item
    save_item || render(:edit)
  end

  def destroy
    load_item
    destroy_item
  end

  private

  def load_items
    @items ||= item_scope.order(:name)
  end

  def load_item
    @item ||= item_scope.find(params[:id])
  end

  def build_item
    @item ||= item_scope.build
    @item.attributes = item_params
  end

  def save_item
    success_notice = if @item.persisted?
                       'Item was successfully updated'
                     else
                       'Item was successfully created'
                     end

    redirect_to @item, notice: success_notice if @item.save
  end

  def destroy_item
    @item.destroy
    redirect_to items_path, notice: 'Item was successfully deleted'
  end

  def item_scope
    Item.all
  end

  def item_params
    item_params = params[:item]
    if item_params
      item_params.permit(:name,
                         :price,
                         stock_effects_attributes: [:id, :stock_id, :change])
    else
      {}
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    load_orders
  end

  def new
    build_order
  end

  def show
    load_order
  end

  def create
    build_order
    save_order || (render :new)
  end

  def edit
    load_order
    build_order
  end

  def update
    load_order
    build_order
    save_order || (render :edit)
  end

  def destroy
    load_order
    destroy_order
  end

  private

  def load_orders
    @orders ||= order_scope.order(:created_at).page(params[:page])
  end

  def load_order
    @order ||= order_scope.find(params[:id])
  end

  def build_order
    @order ||= order_scope.build
    @order.attributes = order_params
    @order.user ||= current_user
  end

  def save_order
    success_notice = if @order.persisted?
                       'Order was successfully updated'
                     else
                       'Order was successfully created'
                     end

    redirect_to @order, notice: success_notice if @order.save
  end

  def destroy_order
    @order.destroy
    redirect_to orders_path, notice: 'Order was successfully deleted'
  end

  def order_scope
    Order.all
  end

  def order_params
    order_params = params[:order]
    if order_params
      order_params.permit(line_items_attributes: [:id, :item_id, :quantity])
    else
      {}
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!

  def index
    load_stocks
  end

  def new
    build_stock
  end

  def show
    load_stock
  end

  def create
    build_stock
    save_stock || render(:new)
  end

  def edit
    load_stock
    build_stock
  end

  def update
    load_stock
    build_stock
    save_stock || render(:edit)
  end

  def destroy
    load_stock
    destroy_stock
  end

  private

  def load_stocks
    @stocks ||= stock_scope.order(:name)
  end

  def load_stock
    @stock ||= stock_scope.find(params[:id])
  end

  def build_stock
    @stock ||= stock_scope.build
    @stock.attributes = stock_params
  end

  def save_stock
    success_notice = if @stock.persisted?
                       'Stock was successfully updated'
                     else
                       'Stock was successfully created'
                     end

    redirect_to @stock, notice: success_notice if @stock.save
  end

  def destroy_stock
    @stock.destroy
    redirect_to stocks_path, notice: 'Stock was successfully deleted.'
  end

  def stock_scope
    Stock.all
  end

  def stock_params
    stock_params = params[:stock]
    if stock_params
      stock_params.permit(:name, :level, :unit)
    else
      {}
    end
  end
end

app/helpers/date_helper.rb
module DateHelper
  def format_date(date)
    date.strftime('%A, %d %b %Y')
  end
end

app/views/home/index.html.haml
.col-md4
  %a.btn.btn-lg.btn-default{href:new_order_path}
    Create an order
  %a.btn.btn-lg.btn-default{href:items_path}
    Configure menu items
  %a.btn.btn-lg.btn-default{href:stocks_path}
    Check stock

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation.alert-warning
      %p= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price, "Price ($)"
    = f.text_field :price
    
  = f.fields_for :stock_effects, @item.current_and_potential_stock_effects do |ff|
    .field.row
      .col-md-2
        = ff.object.stock.name        
        = ff.hidden_field :id
        = ff.hidden_field :stock_id
      .col-md-3
        = ff.label :change, "Reduces stock by (#{ff.object.stock.unit})"
      .col-md-2
        = ff.number_field :change
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Menu items

%table.table
  %thead
    %tr
      %th Name
      %th Cost
      %th
      %th
      %th

  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.price.format
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p
  %b Name:
  = @item.name
%p
  %b Cost:
  = @item.price.format
%p
  Reduces stock by:
- @item.stock_effects.each do |effect|
  %p
    %b= effect.stock.name
    \:
    = effect.change
    = effect.stock.unit
  

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Threadmill
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = javascript_include_tag :application
  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path} Threadmill
        - if signed_in?
          #navbar.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li= link_to "Stock", stocks_path
              %li= link_to "Menu Items", items_path
              %li= link_to "Orders", orders_path
              %li= link_to "Sign Out", destroy_user_session_path
    .container
      .row
        - flash.each do |key, value| 
          = content_tag :p, value, class: "alert alert-#{key}"
    .container
      = yield
      %hr/
      %footer
        %p © Threadmill 2015

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation.alert-warning
      %p= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg

  = f.fields_for :line_items, @order.current_and_potential_line_items do |ff|
    .field.row
      .col-md-2
        = ff.object.item.name 
        = ff.hidden_field :id
        = ff.hidden_field :item_id
      .col-md-2
        = ff.label :quantity
      .col-md-2
        = ff.number_field :quantity
  .actions
    = f.submit 'Save'

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 All orders

%table.table
  %thead
    %tr
      %th Date
      %th Total
      %th
      %th
      %th

  %tbody
    - @orders.each do |order|
      %tr
        %td= format_date(order.created_at)
        %td= order.total.format
        %td= link_to 'Show', order
        %td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
= paginate @orders

= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p
  %b User:
  = @order.user.name
%p
  %b Total:
  = @order.total.format
%p
  %b Line Items:
- @order.line_items.each do |line_item|
  %p
    \#{line_item.item.name} x #{line_item.quantity} @ #{line_item.price_at_purchase.format}
    

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path

app/views/stocks/_form.html.haml
= form_for @stock do |f|
  - if @stock.errors.any?
    #error_explanation.alert-warning
      %p= "#{pluralize(@stock.errors.count, "error")} prohibited this stock from being saved:"
      %ul
        - @stock.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :unit
    = f.text_field :unit
  .actions
    = f.submit 'Save'

app/views/stocks/edit.html.haml
%h1 Editing stock

= render 'form'

= link_to 'Show', @stock
\|
= link_to 'Back', stocks_path

app/views/stocks/index.html.haml
%h1 Listing stocks

%table.table
  %thead
    %tr
      %th Name
      %th Level
      %th
      %th
      %th

  %tbody
    - @stocks.each do |stock|
      %tr
        %td= stock.name
        %td
          = stock.level
          = stock.unit
          - if stock.estimate
            (estimate)
        %td= link_to 'Show', stock
        %td= link_to 'Edit', edit_stock_path(stock)
        %td= link_to 'Destroy', stock, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Stock', new_stock_path

app/views/stocks/new.html.haml
%h1 New stock

= render 'form'

= link_to 'Back', stocks_path

app/views/stocks/show.html.haml
%p
  %b Name:
  = @stock.name
%p
  %b Level:
  = @stock.level
  = @stock.unit
  - if @stock.estimate
    (estimate)

= link_to 'Edit', edit_stock_path(@stock)
\|
= link_to 'Back', stocks_path